name: Synchronous Tests

on:
  pull_request:
    branches: [ master ]

test_success:
  name: Passing submission
  runs-on: ubuntu-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Setup Ruby
    uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
    with:
      ruby-version: 2.6
  - name: Setup Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.8
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      npm install
  - name: Run tests
    run: |
      npm test || pytest || ruby tests/ruby_solution_test.rb
