name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  ruby_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Run tests
      run: ruby tests/ruby_solution_test.rb
  python_test:
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
  javascript_test:
    steps:
    - uses: actions/checkout@v2
    - name: NPM Install
      run: |
        npm install

# language: python

# python:
# - "3.6"

# install:
# - pip install -r requirements.txt
# - npm install

# script:
#     - npm test || pytest || ruby tests/ruby_solution_test.rb || travis_terminate 1
